// src/models/naftaProfessions.js
module.exports = [
  'accountant',
  'architect',
  'computer systems analyst',
  'disaster relief insurance claims adjuster',
  'economist',
  'engineer',
  'forester',
  'graphic designer',
  'hotel manager',
  'industrial designer',
  'interior designer',
  'land surveyor',
  'lawyer',
  'librarian',
  'management consultant',
  'mathematician',
  'medical laboratory technologist',
  'nutritionist',
  'occupational therapist',
  'pharmacist',
  'physician (teaching or research only)',
  'physicist',
  'plant breeder',
  'psychologist',
  'recreational therapist',
  'registered nurse',
  'social worker',
  'soil scientist',
  'scientist',
  'teacher (college, seminary, or university)',
  'urban planner',
  'veterinarian',
  'zoologist'
];
