// src/models/naftaProfessions.js - Complete USMCA/NAFTA Professional List
module.exports = [
  // GENERAL PROFESSIONALS
  'accountant',
  'architect',
  'computer systems analyst',
  'disaster relief insurance claims adjuster',
  'economist',
  'engineer',
  'forester',
  'graphic designer',
  'hotel manager',
  'industrial designer',
  'interior designer',
  'land surveyor',
  'lawyer',
  'librarian',
  'management consultant',
  'mathematician',
  'range manager',
  'research scientist',
  'scientific technician',
  'social worker',
  'sylviculturist',
  'technical publications writer',
  'urban planner',

  // MEDICAL/HEALTHCARE PROFESSIONALS  
  'dentist',
  'medical laboratory technologist',
  'nutritionist',
  'occupational therapist',
  'pharmacist',
  'physician',
  'physician teaching',
  'physician research',
  'physiotherapist',
  'physical therapist',
  'psychologist',
  'recreational therapist',
  'registered nurse',
  'veterinarian',

  // SCIENTISTS
  'agriculturist',
  'animal breeder',
  'animal scientist',
  'apiculturist',
  'astronomer',
  'biochemist',
  'biologist',
  'chemist',
  'dairy scientist',
  'entomologist',
  'epidemiologist',
  'geneticist',
  'geochemist',
  'geologist',
  'geophysicist',
  'horticulturist',
  'meteorologist',
  'pharmacologist',
  'physicist',
  'plant breeder',
  'poultry scientist',
  'soil scientist',
  'zoologist',

  // TEACHERS
  'college teacher',
  'seminary teacher',
  'university teacher',
  'teacher college',
  'teacher seminary',
  'teacher university',

  // TECHNICAL PROFESSIONALS
  'computer programmer',
  'data processing systems analyst',
  'systems analyst',
  'software engineer',
  'database administrator',
  'network administrator',
  'web developer',
  'information systems analyst',

  // Alternative/Common Job Titles (for better matching)
  'software developer',
  'data scientist',
  'business analyst',
  'financial analyst',
  'mechanical engineer',
  'electrical engineer',
  'civil engineer',
  'chemical engineer',
  'industrial engineer',
  'environmental engineer',
  'biomedical engineer',
  'aerospace engineer',
  'petroleum engineer',
  'mining engineer',
  'agricultural engineer',
  'food engineer',
  'systems engineer',
  'network engineer',
  'security engineer',
  'quality engineer',
  'project manager',
  'product manager',
  'marketing manager',
  'sales manager',
  'operations manager',
  'financial manager',
  'human resources manager',
  'it manager',
  'construction manager',
  'research manager',

  // Medical specialties
  'general practitioner',
  'family doctor',
  'internist',
  'pediatrician',
  'surgeon',
  'anesthesiologist',
  'radiologist',
  'pathologist',
  'psychiatrist',
  'dermatologist',
  'ophthalmologist',
  'orthopedist',
  'cardiologist',
  'neurologist',
  'oncologist',
  'emergency physician',
  'family physician',

  // Additional Professional Categories
  'actuary',
  'auditor',
  'tax consultant',
  'financial planner',
  'investment advisor',
  'statistician',
  'market researcher',
  'operations researcher',
  'business consultant',
  'organizational psychologist',
  'clinical psychologist',
  'counseling psychologist',
  'school psychologist',
  'educational psychologist',

  // Architecture & Design
  'landscape architect',
  'interior architect',
  'building architect',
  'urban designer',
  'environmental designer',
  'product designer',
  'user experience designer',
  'user interface designer',
  'multimedia designer',
  'web designer',

  // Legal Professionals
  'attorney',
  'barrister',
  'solicitor',
  'legal counsel',
  'corporate lawyer',
  'immigration lawyer',
  'patent attorney',
  'intellectual property lawyer',

  // Scientific Research
  'laboratory scientist',
  'clinical researcher',
  'biomedical researcher',
  'environmental scientist',
  'food scientist',
  'materials scientist',
  'computer scientist',

  // Abbreviated/Common Terms  
  'cpa',
  'doctor',
  'md',
  'rn',
  'scientist',
  'programmer',
  'developer',
  'analyst',
  'technologist'
];
